# v1
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.4.8"
    hooks:
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --config, pyproject.toml ]